//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class raiser
    {
        public int raiserId { get; set; }
        public Nullable<int> uId { get; set; }

        [Required(ErrorMessage = "Name Required")]
        public string uName { get; set; }

        [Required(ErrorMessage = "Ammount Required")]
        public string uraiseAmount { get; set; }

        [Required(ErrorMessage = "Description Required")]
        public string uDescription { get; set; }

        [Required(ErrorMessage = "Address Required")]
        public string uAddress { get; set; }

        [Required(ErrorMessage = "Email Required")]
        public string uEmail { get; set; }

        [Required(ErrorMessage = "Mobile Required")]
        public string uMobile { get; set; }

        [Required(ErrorMessage = "Date Required")]
        public string Date { get; set; }

        [Required(ErrorMessage = "Image Required")]
        public byte[] image { get; set; }

        [Required(ErrorMessage = "Status Required")]
        public string status { get; set; }
    
        public virtual users1 users1 { get; set; }
    }
}
